name: Setup Code Issue (Form)
description: Submit a setup code issue log item
title: Issue Log Item
body:
  - type: markdown
    attributes:
      value: |
        Please be sure to fill out this form as accurately as possible and select a label for the resolution status
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: false
  - type: input
    id: variables
    attributes:
      label: What variables are affected?
      placeholder: race_hisp_cat5
    validations:
      required: true
  - type: input
    id: subjects
    attributes:
      label: What subjects are affected?
      placeholder: Sample subjects
    validations:
      required: true
  - type: dropdown
    id: dataset
    attributes:
      label: Analytic Dataset
      options:
        - Visits
        - Exits
        - Comorinf
        - Other, specify
      default: 0
    validations:
      required: true
  - type: input
    id: other
    attributes:
      label: Other/specify:
    validations:
      required: false
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
